apiVersion: v1
kind: Pod
metadata:
  name: pod-color-green
  namespace: test
  labels:
   app: web
spec:
  containers:
  - name: app-color-green
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: green
