apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  selector:
    matchLabels:
      app: web-icGroup
  template:
    metadata:
      labels:
        app: web-icGroup
    spec: 
      containers:
      - name: odoo
        image: ngueyepmodeste/ic-group:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ODOO_URL
          value: http://odoo.org
        - name: PGADMIN_URL
          value: http://pgadmin.org  
