apiVersion: v1
kind: Pod
metadata: 
  name: pod-affinity
spec:
  containers: 
  - name: pod
    image: apache
    ports:
    - containerPort: 80
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: app
            operator: In
            values:
              - web
