apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-pod2
  namespace: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /mnt/nfs_share/pod2
    server: 192.168.99.10

