apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pod2
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: nfs-pv-pod2
