apiVersion: v1

kind: Service

metadata:
  name: svc-ip
  namespace: test

spec:
  type: ClusterIP
  ports:
    - port: 80         # Port accessible à l'intérieur du cluster
      targetPort: 3306   # Port sur lequel le pod écoute

  selector:
    app: db-sql
